services:
  pair-presentation:
    container_name: pair-presentation
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pair-presentation.rule=Host(`pair.jesperdsj.dk`)"
      - "traefik.http.routers.pair-presentation.entrypoints=websecure"
      - "traefik.http.routers.pair-presentation.tls.certresolver=myresolver"
      - "traefik.http.services.pair-presentation.loadbalancer.server.port=4173"
    networks:
      - traefik-net
    restart: unless-stopped

networks:
  traefik-net:
    external: true
